### PR TITLE
Fix CCFE 0.3.1+ latest release download

### PR DESCRIPTION
**Pull request by marcojck**
Hi!

Starting from version 0.3.1, CCFE [releases files](https://github.com/linkedin/cruise-control-ui/releases) names have been changed. So this is a small fix to enable the download of the latest CCFE version. 

Thanks!

### CODE REVIEW

**Comment by Raboo** [comment]
Hmm, some questions.
Perhaps we should change so that everyone have to specify UI release?
Or if we still want to use "lastest", isn't it less ugly to use only wget or only curl or woulds that be to much of an work-around?

**Comment by marcojck** [comment]
> Perhaps we should change so that everyone have to specify UI release?

Yah, it could be. Maybe something like this in the Dockerfile:

```bash
ENV CC_VERSION=0.1.39
ENV CCFE_VERSION=latest
```
And than in the `run.sh`:

```bash
if [ "$CCFE_VERSION" = "latest" ]; then
 # Code for get the link of the latest version
else
 # Set the link directly  
fi
```

> Or if we still want to use "lastest", isn't it less ugly to use only wget or only curl or woulds that be to much of an work-around?

The 'wget' was my "quick-and-dirty" solution... indeed only curl ou wget would be better.

**Comment by Raboo** [comment]
Do you want to fix the mentioned stuff or do you want me to merge this quick-fix? For me either works since I don't have time to do it myself right now

**Comment by marcojck** [comment]
Maybe you could accept this fix and as soon as I have time I submit another one with the complete version. Could be?

**Comment by Raboo** [comment]
Sure, it's merged now.

**Comment by marcojck** [comment]
Thanks! Take care!

**Comment by marcojck** [comment]
Hi! Recently I've to move to another Cruise Control docker image because my production environment demands a "offline" image: one that doesn't need Internet access to run. So, unfortunately I will not proceed with the improvements mentioned above. I apologize for that and thank you for your help.

**Comment by Raboo** [comment]
Okay, thanks for letting me know.

**Pull request merged**
